<?php
session_start();
require_once 'vendor/autoload.php';
use Dompdf\Dompdf;
use Dompdf\Options;

if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}

// Database connection
$conn = new mysqli("localhost", "root", "", "wastemanagement");
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Fetch user's past requests
$stmt = $conn->prepare("
    SELECT pr.*, a.area_name 
    FROM pickup_requests pr 
    JOIN areas a ON pr.area_id = a.area_id 
    WHERE pr.user_id = ? AND pr.status = 'completed'
    ORDER BY pr.created_at DESC
");
$stmt->bind_param("i", $_SESSION['user_id']);
$stmt->execute();
$result = $stmt->get_result();
$past_requests = $result->fetch_all(MYSQLI_ASSOC);

// Generate HTML content for PDF
$html = "
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; }
            h1 { color: #333; text-align: center; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #f8f9fa; }
            .header { margin-bottom: 30px; }
            .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #666; }
        </style>
    </head>
    <body>
        <div class='header'>
            <h1>Past Pickup Requests</h1>
            <p>Generated on: " . date("Y-m-d H:i") . "</p>
        </div>
        <table>
            <tr>
                <th>Area</th>
                <th>Pickup Type</th>
                <th>Date Requested</th>
                <th>Weight (kg)</th>
                <th>Status</th>
            </tr>
";

foreach ($past_requests as $request) {
    $html .= "
        <tr>
            <td>{$request['area_name']}</td>
            <td>{$request['pickup_type']}</td>
            <td>" . date("Y-m-d H:i", strtotime($request['created_at'])) . "</td>
            <td>{$request['weight']} kg</td>
            <td>Completed</td>
        </tr>
    ";
}

$html .= "
        </table>
        <div class='footer'>
            <p>Generated by Waste Management System</p>
        </div>
    </body>
    </html>
";

// Configure Dompdf
$options = new Options();
$options->set('isHtml5ParserEnabled', true);
$options->set('isPhpEnabled', true);

// Create PDF
$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

// Output PDF
$dompdf->stream("past_requests_" . date("Y-m-d") . ".pdf", array("Attachment" => true));
?> 